wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.16.3
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1707679516.646523
    t:
      1:
      - 53
      - 55
      2:
      - 53
      - 55
      3:
      - 2
      - 23
      4: 3.11.7
      5: 0.16.3
      8:
      - 1
      - 5
      13: darwin-x86_64
